module.exports = require('jii');

// AUTO-GENERATED Package files list
require('./lib/base/ActiveRecord.js');
require('./lib/base/Collection.js');
require('./lib/base/CollectionAdapterInterface.js');
require('./lib/base/DataProvider.js');
require('./lib/base/Model.js');
require('./lib/base/ModelAdapterInterface.js');
require('./lib/base/ModelAttributeSchema.js');
require('./lib/base/ModelSchema.js');
require('./lib/model/ArrayDataProvider.js');
require('./lib/model/ChangeAttributeEvent.js');
require('./lib/model/ChangeEvent.js');
require('./lib/model/CollectionEvent.js');
require('./lib/model/LinkModelEvent.js');
require('./lib/validators/BooleanValidator.js');
require('./lib/validators/CompareValidator.js');
require('./lib/validators/DateValidator.js');
require('./lib/validators/DefaultValueValidator.js');
require('./lib/validators/EmailValidator.js');
require('./lib/validators/FilterValidator.js');
require('./lib/validators/InlineValidator.js');
require('./lib/validators/NumberValidator.js');
require('./lib/validators/RangeValidator.js');
require('./lib/validators/RegularExpressionValidator.js');
require('./lib/validators/RequiredValidator.js');
require('./lib/validators/SafeValidator.js');
require('./lib/validators/StringValidator.js');
require('./lib/validators/UrlValidator.js');
require('./lib/validators/Validator.js');
