module.exports = require('jii');

// AUTO-GENERATED Package files list
require('./base/ActiveRecord.js');
require('./base/Collection.js');
require('./base/CollectionAdapterInterface.js');
require('./base/DataProvider.js');
require('./base/Model.js');
require('./base/ModelAdapterInterface.js');
require('./base/ModelAttributeSchema.js');
require('./base/ModelSchema.js');
require('./model/ArrayDataProvider.js');
require('./model/ChangeAttributeEvent.js');
require('./model/ChangeEvent.js');
require('./model/CollectionEvent.js');
require('./model/ValidateEvent.js');
require('./validators/BooleanValidator.js');
require('./validators/CompareValidator.js');
require('./validators/DateValidator.js');
require('./validators/DefaultValueValidator.js');
require('./validators/EmailValidator.js');
require('./validators/FilterValidator.js');
require('./validators/InlineValidator.js');
require('./validators/NumberValidator.js');
require('./validators/RangeValidator.js');
require('./validators/RegularExpressionValidator.js');
require('./validators/RequiredValidator.js');
require('./validators/SafeValidator.js');
require('./validators/StringValidator.js');
require('./validators/UrlValidator.js');
require('./validators/Validator.js');
